// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "assistant/api/services"

var reportTypes = services.GetReportTypes()

func GenerateReportDialog() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<dialog id=\"generateReportDialog\" class=\"bg-gray-800 text-white rounded-lg p-2 backdrop:bg-black/80\"><div class=\"w-[30rem] max-w-[95%] p-6 relative\"><button class=\"absolute top-2 right-2 text-gray-200 hover:text-gray-100 focus:outline-none\" onclick=\"closeDialog()\"><svg class=\"h-6 w-6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" viewBox=\"0 0 24 24\"><line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\"></line> <line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\"></line></svg></button><form class=\"group\" hx-post=\"/generate-report\" hx-trigger=\"submit\" hx-target=\"main\" hx-swap=\"outerHTML show:#messageList:bottom\" hx-disabled-elt=\"find select, find textarea, find button\"><h2 class=\"text-2xl text-center font-semibold mt-1 mb-3\">Generate Report</h2><div class=\"mb-4\"><label for=\"reportType\" class=\"block text-sm font-medium mb-1\">Type</label> <select name=\"reportType\" id=\"reportType\" class=\"w-full bg-gray-800 border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 mb-5\" id=\"type\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, reportType := range reportTypes {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option class=\"bg-gray-800\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(reportType)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `api/assets/templ/components/generate_report_dialog.templ`, Line: 24, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(reportType)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `api/assets/templ/components/generate_report_dialog.templ`, Line: 24, Col: 76}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select> <label for=\"additionalMessage\" class=\"block text-sm font-medium mb-1\">Additonal Message</label> <textarea name=\"additionalMessage\" id=\"additionalMessage\" rows=\"3\" id=\"additionalMessage\" class=\"w-full bg-gray-800 border border-gray-300 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500\"></textarea></div><button type=\"submit\" class=\"w-full bg-blue-400 text-white font-semibold py-2 rounded-lg hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-200 focus:ring-offset-2\" hx-disabled><span class=\"w-4 h-4 -rotate-90 group-[.htmx-request]:hidden\">Generate</span> <span class=\"htmx-indicator hidden group-[.htmx-request]:inline\" stroke=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 384 512\">Please wait</span></button></form></div></dialog><script>\n    function openDialog() {\n      document.getElementById('generateReportDialog')?.showModal();\n    }\n    function closeDialog() {\n      document.getElementById('generateReportDialog').close();\n    }\n\n    document.getElementById('generateReportDialog').addEventListener(\"htmx:responseError\", () => document.getElementById('generateReportDialog').close());\n    document.getElementById('generateReportDialog').addEventListener(\"htmx:afterRequest\", () => document.getElementById('generateReportDialog').close());\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
