# Fill in with your keys and RPC urls, rename to api_keys.sh (gitignored) and then run
# source api_keys.sh

#export OPENAI_API_KEY=""
#export ANTHROPIC_API_KEY=""
#export ETHERSCAN_API_KEY=""
#export OPTIMISTIC_ETHERSCAN_API_KEY=""
#export BSCSCAN_API_KEY=""
#export ARBISCAN_API_KEY=""
#export POLYGONSCAN_API_KEY=""
#export SNOWTRACE_API_KEY=""
#export FTMSCAN_API_KEY=""

#export ECHIDNA_RPC_URL_MAINNET=""
#export ECHIDNA_RPC_URL_OPTIMISM=""
#export ECHIDNA_RPC_URL_ROPSTEN=""
#export ECHIDNA_RPC_URL_KOVAN=""
#export ECHIDNA_RPC_URL_RINKEBY=""
#export ECHIDNA_RPC_URL_GOERLI=""
#export ECHIDNA_RPC_URL_TOBALABA=""
#export ECHIDNA_RPC_URL_BSC=""
#export ECHIDNA_RPC_URL_BSC_TESTNET=""
#export ECHIDNA_RPC_URL_ARBI=""
#export ECHIDNA_RPC_URL_ARBI_TESTNET=""
#export ECHIDNA_RPC_URL_POLY=""
#export ECHIDNA_RPC_URL_MUMBAI=""
#export ECHIDNA_RPC_URL_AVAX=""
#export ECHIDNA_RPC_URL_AVAX_TESTNET=""
#export ECHIDNA_RPC_URL_FTM=""
